# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"2\n\x05\x45rror\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x91\x01\n\x07Request\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\t\x12\x16\n\x0eresource_names\x18\x03 \x03(\t\x12\x19\n\x11resource_locators\x18\x04 \x03(\t\x12\x16\n\x0eresponse_nonce\x18\x05 \x01(\t\x12\x1c\n\x0c\x65rror_detail\x18\x06 \x01(\x0b\x32\x06.Error\"h\n\tresources\x12*\n\x08resource\x18\x01 \x03(\x0b\x32\x18.resources.ResourceEntry\x1a/\n\rResourceEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"`\n\x08Response\x12\x14\n\x0cversion_info\x18\x01 \x01(\t\x12\x1d\n\tresources\x18\x02 \x03(\x0b\x32\n.resources\x12\r\n\x05nonce\x18\x03 \x01(\t\x12\x10\n\x08ServerId\x18\x04 \x01(\t\"3\n\x0b\x43lientHello\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_data\x18\x02 \x01(\t\"3\n\x0bServerHello\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\x12\x17\n\x0fresponse_string\x18\x02 \x01(\t24\n\x08\x43ommTest\x12(\n\x08Identify\x12\x0c.ClientHello\x1a\x0c.ServerHello\"\x00\x32\x44\n\x14\x43lient1Communication\x12,\n\x0fStreamResources\x12\x08.Request\x1a\t.Response\"\x00(\x01\x30\x01\x32\x44\n\x14\x43lient2Communication\x12,\n\x0fStreamResources\x12\x08.Request\x1a\t.Response\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESOURCES_RESOURCEENTRY']._options = None
  _globals['_RESOURCES_RESOURCEENTRY']._serialized_options = b'8\001'
  _globals['_ERROR']._serialized_start=16
  _globals['_ERROR']._serialized_end=66
  _globals['_REQUEST']._serialized_start=69
  _globals['_REQUEST']._serialized_end=214
  _globals['_RESOURCES']._serialized_start=216
  _globals['_RESOURCES']._serialized_end=320
  _globals['_RESOURCES_RESOURCEENTRY']._serialized_start=273
  _globals['_RESOURCES_RESOURCEENTRY']._serialized_end=320
  _globals['_RESPONSE']._serialized_start=322
  _globals['_RESPONSE']._serialized_end=418
  _globals['_CLIENTHELLO']._serialized_start=420
  _globals['_CLIENTHELLO']._serialized_end=471
  _globals['_SERVERHELLO']._serialized_start=473
  _globals['_SERVERHELLO']._serialized_end=524
  _globals['_COMMTEST']._serialized_start=526
  _globals['_COMMTEST']._serialized_end=578
  _globals['_CLIENT1COMMUNICATION']._serialized_start=580
  _globals['_CLIENT1COMMUNICATION']._serialized_end=648
  _globals['_CLIENT2COMMUNICATION']._serialized_start=650
  _globals['_CLIENT2COMMUNICATION']._serialized_end=718
# @@protoc_insertion_point(module_scope)
