# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import schema_pb2 as schema__pb2


class CommTestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Identify = channel.unary_unary(
                '/CommTest/Identify',
                request_serializer=schema__pb2.ClientHello.SerializeToString,
                response_deserializer=schema__pb2.ServerHello.FromString,
                )


class CommTestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Identify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommTestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Identify': grpc.unary_unary_rpc_method_handler(
                    servicer.Identify,
                    request_deserializer=schema__pb2.ClientHello.FromString,
                    response_serializer=schema__pb2.ServerHello.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommTest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommTest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Identify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommTest/Identify',
            schema__pb2.ClientHello.SerializeToString,
            schema__pb2.ServerHello.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class Client1CommunicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamResources = channel.stream_stream(
                '/Client1Communication/StreamResources',
                request_serializer=schema__pb2.Request.SerializeToString,
                response_deserializer=schema__pb2.Response.FromString,
                )


class Client1CommunicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamResources(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Client1CommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamResources': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamResources,
                    request_deserializer=schema__pb2.Request.FromString,
                    response_serializer=schema__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Client1Communication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Client1Communication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamResources(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Client1Communication/StreamResources',
            schema__pb2.Request.SerializeToString,
            schema__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class Client2CommunicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamResources = channel.stream_stream(
                '/Client2Communication/StreamResources',
                request_serializer=schema__pb2.Request.SerializeToString,
                response_deserializer=schema__pb2.Response.FromString,
                )


class Client2CommunicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamResources(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Client2CommunicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamResources': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamResources,
                    request_deserializer=schema__pb2.Request.FromString,
                    response_serializer=schema__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Client2Communication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Client2Communication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamResources(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Client2Communication/StreamResources',
            schema__pb2.Request.SerializeToString,
            schema__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
